version: '3.8'

services:
  postgres:
    image: postgres:12.18-bullseye
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: bhejio
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.4-bookworm
    container_name: redis-container
    environment:
      REDIS_PASSWORD: 12345678
    command: ['redis-server', '--requirepass', '12345678']
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
